/* Sifr Collection, country profiles for the 12 coverage nations.
   Net-zero and NDC facts from public sources. Projects are cross-referenced from projects-data.js at runtime. */
window.SIFR_COUNTRIES = {
  updated: "2026-06-22",
  items: [
    { id:"ksa", cc:"KSA", name:"Saudi Arabia", flag:"🇸🇦",
      netZero:"2060", ndc:"278 MtCO₂e annual reduction by 2030",
      schemes:["rvcmc","gcom","sgi"], bodies:["Public Investment Fund","RVCMC","Tadawul","Ministry of Environment, Water and Agriculture"],
      summary:"The region's most developed voluntary market and the largest CCS pipeline.",
      detail:"Net zero by 2060, anchored by the Saudi Green Initiative (10 billion trees) and the Circular Carbon Economy framework. RVCMC runs the voluntary market while GCOM is building a national crediting mechanism. Aramco's Jubail hub is one of the world's largest planned CCUS projects." },
    { id:"uae", cc:"UAE", name:"United Arab Emirates", flag:"🇦🇪",
      netZero:"2050", ndc:"47% reduction by 2035 (third NDC)",
      schemes:["acx","adgm","uae-climate-law","uae-ncsp"], bodies:["MOCCAE","ADGM","Masdar","ADNOC"],
      summary:"First Gulf net-zero pledge, first regulated exchange, first binding climate law.",
      detail:"The first Gulf state to commit to net zero (2050), host of COP28, and the regulatory frontrunner. ADGM regulates credits as financial instruments, ACX runs the first regulated exchange, and the Federal Climate Law makes emissions reporting mandatory from 2026. ADNOC's Habshan CCS and 100 million mangroves anchor supply." },
    { id:"omn", cc:"OMN", name:"Oman", flag:"🇴🇲",
      netZero:"2050", ndc:"7% reduction by 2030",
      schemes:[], bodies:["Ministry of Energy and Minerals","Environment Authority","Hydrom"],
      summary:"Net zero by 2050, home to a world-first permanent removal project.",
      detail:"Net zero by 2050 with an energy-transition roadmap built around green hydrogen (Hydrom) and the unique geology of the Hajar Mountains. 44.01's Project Hajar is the world's first commercial-scale peridotite mineralisation concession, producing premium permanent removal credits." },
    { id:"qat", cc:"QAT", name:"Qatar", flag:"🇶🇦",
      netZero:"No firm year", ndc:"25% reduction by 2030",
      schemes:[], bodies:["QatarEnergy","Ministry of Environment and Climate Change"],
      summary:"No net-zero year yet, but major CCS tied to North Field LNG.",
      detail:"Qatar has a 25% emissions-reduction target by 2030 but no firm net-zero year, the Gulf outlier. Its carbon story is led by QatarEnergy's CCS programme at Ras Laffan, targeting more than 11 Mtpa across assets by 2035 alongside North Field LNG expansion." },
    { id:"bhr", cc:"BHR", name:"Bahrain", flag:"🇧🇭",
      netZero:"2060", ndc:"30% reduction by 2035",
      schemes:[], bodies:["Supreme Council for Environment"],
      summary:"Net zero by 2060, early-stage market activity.",
      detail:"Net zero by 2060 with interim reduction targets. Carbon market and project activity is early-stage, focused on energy efficiency, mangrove and seagrass blue carbon, and renewable deployment." },
    { id:"kwt", cc:"KWT", name:"Kuwait", flag:"🇰🇼",
      netZero:"2060", ndc:"Conditional reduction target",
      schemes:[], bodies:["Environment Public Authority","Kuwait Petroleum Corporation"],
      summary:"Net zero by 2060 for total emissions, oil sector by 2050.",
      detail:"Kuwait targets net zero across total emissions by 2060, and across the oil and gas sector by 2050. Market and project infrastructure is nascent, with decarbonisation led by the national oil company." },
    { id:"egy", cc:"EGY", name:"Egypt", flag:"🇪🇬",
      netZero:"No firm year", ndc:"Conditional sector targets to 2030",
      schemes:["egypt-vcm"], bodies:["Financial Regulatory Authority","Ministry of Environment","Egyptian Exchange"],
      summary:"Africa's first regulated voluntary carbon market; host of COP27.",
      detail:"Egypt hosted COP27 and launched a regulated voluntary carbon market under the Financial Regulatory Authority, trading on the Egyptian Exchange. No firm net-zero year, but strong renewable build-out (Benban, one of the world's largest solar parks) generating reduction credits." },
    { id:"jor", cc:"JOR", name:"Jordan", flag:"🇯🇴",
      netZero:"No firm year", ndc:"31% reduction by 2030 (with support)",
      schemes:[], bodies:["Ministry of Environment"],
      summary:"Strong renewables, a 31% reduction NDC, pioneering regional wind.",
      detail:"Jordan targets a 31% emissions reduction by 2030, largely conditional on international support. Home to Tafila, the region's first utility-scale wind farm, and active in dryland restoration in the Rift Valley." },
    { id:"irq", cc:"IRQ", name:"Iraq", flag:"🇮🇶",
      netZero:"No firm year", ndc:"Conditional reduction, gas-flaring focus",
      schemes:[], bodies:["Ministry of Environment"],
      summary:"Early-stage, focused on gas-flaring and wetland restoration.",
      detail:"Iraq's climate effort centres on cutting gas flaring and protecting the UNESCO-listed Mesopotamian marshes. Carbon market infrastructure is nascent and constrained by reconstruction priorities." },
    { id:"lbn", cc:"LBN", name:"Lebanon", flag:"🇱🇧",
      netZero:"No firm year", ndc:"20% reduction by 2030 (with support)",
      schemes:[], bodies:["Ministry of Environment"],
      summary:"NDC in place, but action constrained by economic crisis.",
      detail:"Lebanon has a 20% reduction NDC by 2030, mostly conditional on support. Economic crisis and instability limit market development; activity is concentrated in donor-funded reforestation and energy projects." },
    { id:"syr", cc:"SYR", name:"Syria", flag:"🇸🇾",
      netZero:"No firm year", ndc:"Limited",
      schemes:[], bodies:["Ministry of Local Administration and Environment"],
      summary:"Minimal market activity, conflict-affected.",
      detail:"Syria has minimal carbon market infrastructure given years of conflict. Tracked for completeness of regional coverage rather than active project flow." },
    { id:"yem", cc:"YEM", name:"Yemen", flag:"🇾🇪",
      netZero:"No firm year", ndc:"Conditional, adaptation-focused",
      schemes:[], bodies:["Environment Protection Authority"],
      summary:"Adaptation-focused, minimal market activity.",
      detail:"Yemen's climate engagement is adaptation-focused and constrained by conflict. Limited project flow; tracked for completeness of coverage." }
  ]
};
