/* Sifr Collection, intelligence feed.
   Regenerated by the daily data-refresh job. Items are real, public, and dated. */
window.SIFR_NEWS = {
  updated: "2026-06-22",
  items: [
    { date:"Jun 2026", tag:"Policy", text:"Saudi Arabia is advancing its Greenhouse Gas Crediting and Offsetting Mechanism (GCOM), its national crediting framework, alongside the RVCMC voluntary market.", source:"Saudi Arabia", url:"https://vcm.sa/" },
    { date:"2026", tag:"Market", text:"RVCMC has a long-term agreement to deliver more than 30 million tonnes of carbon credits by 2030, on top of 6.1M tonnes already auctioned across 2022 to 2024.", source:"RVCMC", url:"https://vcm.sa/" },
    { date:"2026", tag:"Project", text:"UAE targets 100 million mangroves by 2030 under the National Carbon Sequestration Project, with more than 30 million already planted.", source:"UAE MOCCAE", url:"https://www.moccae.gov.ae/" },
    { date:"2025", tag:"Market", text:"Nature-based removal credits reached about $24 per tonne in 2025, up from roughly $14 at the start of the year, as buyers shifted toward higher-integrity removals.", source:"Market reporting", url:"https://carboncredits.com/" },
    { date:"Active", tag:"Policy", text:"ADGM in Abu Dhabi regulates voluntary carbon credits as financial instruments; ACX operates the first fully regulated carbon exchange and clearing house.", source:"ADGM / ACX", url:"https://www.adgm.com/" },
    { date:"2026", tag:"Policy", text:"Egypt has launched its voluntary carbon market, adding a second large North African venue alongside the Gulf's exchanges.", source:"Egypt", url:"https://www.fra.gov.eg/" },
    { date:"Active", tag:"Project", text:"Red Sea Global targets 50 million mangroves by 2030, with more than 3 million seedlings already cultivated along the Saudi Red Sea coast.", source:"Red Sea Global", url:"https://www.redseaglobal.com/" }
  ]
};
