/* Sifr Collection, intelligence feed.
   Regenerated by the daily data-refresh job. Items are real, public, and dated. */
window.SIFR_NEWS = {
  updated: "2026-06-29",
  items: [
    { date:"Jun 2026", tag:"Market", text:"EU ETS allowance prices traded near €81.35 per tonne in late June 2026, the highest since February, supported by roughly 8 percent lower allowance supply in 2026 and ETS reform expectations.", source:"Trading Economics", url:"https://tradingeconomics.com/commodity/carbon" },
    { date:"Jun 2026", tag:"Policy", text:"The UAE Climate Law compliance deadline of 30 May 2026 has passed, so all public and private entities, including free zones, are now legally required to measure, report and reduce emissions, with fines up to AED 2,000,000.", source:"Arbor", url:"https://www.arbor.eco/blog/uae-climate-change-reduction-law" },
    { date:"Jun 2026", tag:"Market", text:"Saudi Arabia's RVCMC is moving toward a 2027 exchange launch and signalled a phased carbon compliance system by 2028 that builds on its existing voluntary market before adding regulation.", source:"Carbon Herald", url:"https://carbonherald.com/saudi-arabia-moves-closer-to-2027-carbon-market-launch/" },
    { date:"12 Jun 2026", tag:"Market", text:"Singapore signed cooperation agreements with Verra and Gold Standard to expand its role in project validation and verification under Article 6, the credit supply that MENA buyers increasingly draw on.", source:"Carbon Pulse", url:"https://carbon-pulse.com/521478/" },
    { date:"Jun 2026", tag:"Policy", text:"Verra operationalised VCS Version 5, releasing updated templates that become mandatory for all project requests submitted after 1 January 2027.", source:"Carbon Pulse", url:"https://carbon-pulse.com/519345/" },
    { date:"18 Jun 2026", tag:"Soil Carbon", text:"Saudi KAUST spinout Terraxy raised $3 million led by Aramco's Wa'ed Ventures to scale its CarboSoil desert soil enhancer, which stores carbon in arid soils, including a 30,000 square metre plant in Al Zulfi.", source:"Carbon Herald", url:"https://carbonherald.com/terraxy-to-scale-soil-regeneration-tech-with-new-3m-from-aramcos-waed-ventures-kaust/" },
    { date:"2026", tag:"Project", text:"Oman's Environment Authority and MSA Green Projects are advancing the Oman Blue Carbon project to cultivate up to 100 million mangrove trees, targeting around 14 million tonnes of CO2 removed and roughly $150 million in carbon credits.", source:"Carbon Credits", url:"https://carboncredits.com/omans-mangrove-restoration-could-generate-150-million-in-carbon-credits/" },
    { date:"2026", tag:"Project", text:"Saudi Aramco's Jubail carbon capture hub, with SLB and Linde, targets up to 9 million tonnes of CO2 captured a year by 2027, scaling toward 44 million tonnes by 2035.", source:"Saudipedia", url:"https://saudipedia.com/en/carbon-capture-in-saudi-arabia" }
  ]
};
