/* Sifr Collection, intelligence feed.
   Regenerated by the daily data-refresh job. Items are real, public, and dated. */
window.SIFR_NEWS = {
  updated: "2026-07-08",
  items: [
    { date:"6 Jul 2026", tag:"Policy", text:"EU lawmakers voted to extend the Carbon Border Adjustment Mechanism to more than 400 downstream products. Gulf exporters of aluminium, steel and fertiliser derivatives face a wider CBAM perimeter than the original six sectors.", source:"Carbon Pulse", url:"https://carbon-pulse.com/529093/" },
    { date:"5 Jul 2026", tag:"Market", text:"Carbon Pulse's monthly MENA roundup found Gulf countries spent June building domestic voluntary carbon markets through a mix of incentives, mandates and capacity support, deepening the regional project pipeline.", source:"Carbon Pulse", url:"https://carbon-pulse.com/528595/" },
    { date:"6 Jul 2026", tag:"Market", text:"CORSIA-eligible credits edged back to about $10 per tonne ahead of the EU's assessment of the scheme, and analysts revised down their demand outlook. Gulf carriers price their offsetting obligation off this benchmark.", source:"Carbon Pulse", url:"https://carbon-pulse.com/528813/" },
    { date:"7 Jul 2026", tag:"Market", text:"EU allowances gave up Monday's gains across a full day of selling, even with EU auction volumes set to fall as the REPowerEU programme ends on Thursday. Gas rallied after an LNG tanker was attacked overnight.", source:"Carbon Pulse", url:"https://carbon-pulse.com/529236/" },
    { date:"6 Jul 2026", tag:"Market", text:"The Macao International Carbon Emission Exchange listed spot contracts for ICVCM Core Carbon Principles labelled credits, the first exchange-traded product tied specifically to the CCP integrity tier.", source:"Carbon Pulse", url:"https://carbon-pulse.com/529195/" },
    { date:"7 Jul 2026", tag:"Soil Carbon", text:"Verra will require sustainable grasslands projects to validate soil carbon models against measured change over time rather than one-off stock measurements. Arid-land soil carbon projects in the Gulf will need longer measurement records to qualify.", source:"Carbon Pulse", url:"https://carbon-pulse.com/529467/" },
    { date:"7 Jul 2026", tag:"Policy", text:"Gold Standard added a fifth approved insurance policy to its list of accepted covers for CORSIA, widening the routes for airlines to insure reversal risk on offset credits.", source:"Carbon Pulse", url:"https://carbon-pulse.com/529023/" },
    { date:"6 Jul 2026", tag:"Project", text:"The World Bank approved $265 million for a pumped-storage hydropower project in Morocco, its largest MENA clean power commitment this year, even as the bank retreats from firm climate targets.", source:"Carbon Pulse", url:"https://carbon-pulse.com/528971/" }
  ]
};
