/* Sifr Collection, project dataset.
   Single source of truth for the map, the table, the project cards and the detail panels.
   The detail panel shows the full record; cards show a summary.
   This file can be regenerated by the daily data-refresh job. */
window.SIFR_PROJECTS = [
  {
    id:"qassim", name:"Qassim Soil Restoration", flag:"🇸🇦", cc:"KSA", country:"Saudi Arabia",
    type:"soil", nature:"Removal", status:"Active", lat:26.33, lon:43.97,
    area:"95,000 ha", annual:"420,000 tCO₂e/yr", std:"Verra VCS", methodology:"VM0042 (improved agricultural land management)",
    registry:"Verra", vintage:"2024 onward", lifetime:"30 years", developer:"Regional developer (public sources)",
    price:"$28.90", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Rangeland restoration","Soil fertility and water retention","Rural livelihoods"],
    summary:"Rangeland soil organic carbon enhancement across Al-Qassim.",
    detail:"Soil organic carbon enhancement across degraded rangeland in Al-Qassim, combining biochar application, managed grazing and native species planting. Arid soils hold little carbon per hectare, so credibility rests on field measurement against a VM0042 baseline rather than satellite estimates alone.",
    url:"https://registry.verra.org/"
  },
  {
    id:"abudhabi", name:"Abu Dhabi Soil Sequestration", flag:"🇦🇪", cc:"UAE", country:"United Arab Emirates",
    type:"soil", nature:"Removal", status:"Active", lat:24.45, lon:54.37,
    area:"42,000 ha", annual:"168,000 tCO₂e/yr", std:"Verra VCS", methodology:"Soil carbon (VM0042 family)",
    registry:"Verra", vintage:"2024 onward", lifetime:"25 years", developer:"Regional developer (public sources)",
    price:"$24.80", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Desert greening","Dust suppression","Native shrub habitat"],
    summary:"Compost and native shrub planting on Abu Dhabi sandy substrate.",
    detail:"An early at-scale arid soil carbon effort in the Abu Dhabi hinterland, using compost amendment and deep-rooted native desert shrubs on sandy substrate. Tracked as a developing soil carbon project; sequestration rates on this substrate are modest and depend on irrigation and management.",
    url:"https://registry.verra.org/"
  },
  {
    id:"alula", name:"AlUla Desert Ecosystem", flag:"🇸🇦", cc:"KSA", country:"Saudi Arabia",
    type:"land", nature:"Removal", status:"Active", lat:26.62, lon:37.95,
    area:"180,000 ha", annual:"680,000 tCO₂e/yr", std:"Verra VCS", methodology:"Afforestation, reforestation and revegetation (ARR)",
    registry:"Verra", vintage:"2024 onward", lifetime:"30 years", developer:"Royal Commission for AlUla",
    price:"$18.20", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Native juniper and acacia woodland","Biodiversity","Cultural heritage landscape"],
    summary:"Native woodland restoration under the Royal Commission for AlUla.",
    detail:"Landscape restoration under the Royal Commission for AlUla, restoring native juniper and acacia woodland across the Hejaz mountains as part of a public initiative. Sits within a UNESCO-listed heritage landscape, so co-benefits around biodiversity and heritage carry weight alongside the carbon.",
    url:"https://www.rcu.gov.sa/en"
  },
  {
    id:"niledelta", name:"Nile Delta Mangrove", flag:"🇪🇬", cc:"EGY", country:"Egypt",
    type:"blue", nature:"Removal", status:"Active", lat:31.2, lon:31.0,
    area:"12,000 ha", annual:"96,000 tCO₂e/yr", std:"Verra VCS", methodology:"VM0033 (tidal wetland and seagrass restoration)",
    registry:"Verra", vintage:"2024 onward", lifetime:"30 years", developer:"Regional developer (public sources)",
    price:"$41.20", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Coastal protection","Fisheries nursery habitat","High permanence blue carbon"],
    summary:"Mangrove and coastal wetland restoration in the northern Nile Delta.",
    detail:"Mangrove restoration and coastal ecosystem rehabilitation across degraded wetlands in the northern Nile Delta. Blue carbon stores carbon densely and tends to price at a premium, but coastal projects carry permanence and tenure risks that buyers scrutinise.",
    url:"https://registry.verra.org/"
  },
  {
    id:"dhofar", name:"Dhofar Rangeland", flag:"🇴🇲", cc:"OMN", country:"Oman",
    type:"soil", nature:"Removal", status:"Active", lat:17.0, lon:54.1,
    area:"67,000 ha", annual:"185,000 tCO₂e/yr", std:"Gold Standard", methodology:"Soil organic carbon, managed grazing",
    registry:"Gold Standard", vintage:"2024 onward", lifetime:"20 years", developer:"Regional developer (public sources)",
    price:"$26.40", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Monsoon grassland recovery","Pastoralist livelihoods","Erosion control"],
    summary:"Managed rangeland rehabilitation on Dhofar's monsoon plateau.",
    detail:"Managed rangeland rehabilitation on Dhofar's highland plateau, drawing on the Khareef monsoon that sets this region apart from the wider peninsula and supports faster vegetation recovery than typical Gulf drylands. Gold Standard typically prices at a premium to comparable Verra credits.",
    url:"https://www.goldstandard.org/"
  },
  {
    id:"mesopotamia", name:"Mesopotamia Marshes", flag:"🇮🇶", cc:"IRQ", country:"Iraq",
    type:"redd", nature:"Avoidance", status:"Pending", lat:30.9, lon:47.0,
    area:"55,000 ha", annual:"220,000 tCO₂e/yr (est.)", std:"Verra VCS", methodology:"Wetland conservation (VM0007 / REDD+ family)",
    registry:"Verra", vintage:"Targeting 2026", lifetime:"30 years", developer:"Public, UNESCO World Heritage site",
    price:"Indicative", priceUnit:"avoidance credit class",
    coBenefits:["UNESCO heritage protection","Reed-bed biodiversity","Water and marsh restoration"],
    summary:"Protection of the UNESCO-listed Mesopotamian marshes.",
    detail:"Protection and restoration of the Mesopotamian marshes, a UNESCO World Heritage site, avoiding emissions from drainage and degradation of the reed beds. As an avoidance project it sits at the lower-quality end of the spectrum on integrity grounds, so baseline and additionality evidence will be decisive.",
    url:"https://whc.unesco.org/en/list/1481/"
  },
  {
    id:"redsea", name:"Red Sea Mangrove Belt", flag:"🇸🇦", cc:"KSA", country:"Saudi Arabia",
    type:"blue", nature:"Removal", status:"Development", lat:22.0, lon:38.5,
    area:"52,000 ha", annual:"n/a yet", std:"Verra VCS", methodology:"VM0033 (tidal wetland restoration)",
    registry:"Verra", vintage:"Targeting late decade", lifetime:"30 years", developer:"Red Sea Global",
    price:"Indicative", priceUnit:"blue carbon class",
    coBenefits:["50M mangroves by 2030 target","Coastal resilience","Tourism and conservation"],
    summary:"Red Sea Global's 50 million mangrove commitment.",
    detail:"Red Sea Global has publicly committed to planting 50 million mangroves by 2030 along the Saudi Red Sea coast, with more than 3 million seedlings already cultivated. One of the region's most watched blue carbon efforts; credit issuance volumes will depend on survival rates and methodology approval.",
    url:"https://www.redseaglobal.com/"
  },
  {
    id:"jordan", name:"Jordan Valley Watershed", flag:"🇯🇴", cc:"JOR", country:"Jordan",
    type:"land", nature:"Removal", status:"Development", lat:32.0, lon:35.6,
    area:"28,000 ha", annual:"84,000 tCO₂e/yr", std:"Verra VCS", methodology:"ARR, dryland forest recovery",
    registry:"Verra", vintage:"Targeting 2027", lifetime:"30 years", developer:"Regional developer (public sources)",
    price:"$12.50", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Watershed protection","Mediterranean dryland forest","Soil stabilisation"],
    summary:"Watershed and dryland forest recovery in the Jordan Rift Valley.",
    detail:"Watershed restoration and native Mediterranean dryland forest recovery across the Jordan Rift Valley hillsides, with verification expected in the coming years. Early-stage, so the indicative price reflects pre-verification risk.",
    url:"https://registry.verra.org/"
  },
  {
    id:"neom", name:"NEOM Green Spine", flag:"🇸🇦", cc:"KSA", country:"Saudi Arabia",
    type:"land", nature:"Removal", status:"Development", lat:27.9, lon:35.5,
    area:"320,000 ha", annual:"1,200,000 tCO₂e/yr", std:"Gold Standard", methodology:"ARR, landscape restoration",
    registry:"Gold Standard", vintage:"Targeting late decade", lifetime:"30 years", developer:"NEOM",
    price:"$31.10", priceUnit:"indicative ref / tCO₂e",
    coBenefits:["Large-scale reforestation","Desert ecosystem restoration","Part of NEOM development"],
    summary:"One of the region's largest announced desert reforestation efforts.",
    detail:"A large landscape restoration and reforestation programme across the mountainous terrain of Tabuk, part of the NEOM public development. One of the region's largest announced desert reforestation efforts; scale and water availability will determine how much of the headline figure is realised.",
    url:"https://www.neom.com/"
  },
  {
    id:"habshan", name:"ADNOC Habshan CCS", flag:"🇦🇪", cc:"UAE", country:"United Arab Emirates",
    type:"capture", nature:"Reduction", status:"Development", lat:24.05, lon:53.65,
    area:"Industrial site", annual:"1,500,000 tCO₂e/yr capture", std:"CCS, operational", methodology:"Carbon capture and geological storage",
    registry:"Not a credit listing", vintage:"n/a", lifetime:"Asset life", developer:"ADNOC",
    price:"n/a", priceUnit:"operational decarbonisation",
    coBenefits:["Triples ADNOC capture to 2.3 Mtpa","Feeds 10 Mtpa-by-2030 target","Permanent geological storage"],
    summary:"1.5 Mtpa capture, building on Al Reyadah CCUS.",
    detail:"Capture and permanent storage of 1.5 million tonnes a year, tripling ADNOC capture capacity to 2.3 Mtpa toward a 10 Mtpa 2030 target. Builds on Al Reyadah, the region's first commercial CCUS plant. This is operational decarbonisation of ADNOC's own emissions, not a voluntary credit listing, but it is central to the region's carbon picture.",
    url:"https://www.adnoc.ae/"
  },
  {
    id:"jubail", name:"Aramco Jubail CCUS Hub", flag:"🇸🇦", cc:"KSA", country:"Saudi Arabia",
    type:"capture", nature:"Reduction", status:"Development", lat:27.0, lon:49.65,
    area:"Industrial hub", annual:"9,000,000 tCO₂e/yr by 2027", std:"CCUS, operational", methodology:"Carbon capture, utilisation and storage",
    registry:"Not a credit listing", vintage:"n/a", lifetime:"Asset life", developer:"Aramco, SLB, Linde",
    price:"n/a", priceUnit:"operational decarbonisation",
    coBenefits:["Up to 44 Mtpa by 2035","One of the world's largest CCUS hubs","Joint venture scale"],
    summary:"9 Mtpa by 2027, scaling to 44 Mtpa by 2035.",
    detail:"One of the world's largest planned CCUS hubs, targeting 9 million tonnes a year by 2027 and up to 44 Mtpa by 2035 on the Saudi east coast, developed by Aramco with SLB and Linde. Operational capture rather than a credit listing, but the volumes dwarf the region's voluntary market.",
    url:"https://www.aramco.com/"
  },
  {
    id:"raslaffan", name:"QatarEnergy Ras Laffan CCS", flag:"🇶🇦", cc:"QAT", country:"Qatar",
    type:"capture", nature:"Reduction", status:"Development", lat:25.9, lon:51.55,
    area:"Industrial site", annual:"4,000,000 tCO₂e/yr by 2030", std:"CCS, operational", methodology:"Carbon capture and storage",
    registry:"Not a credit listing", vintage:"n/a", lifetime:"Asset life", developer:"QatarEnergy",
    price:"n/a", priceUnit:"operational decarbonisation",
    coBenefits:["More than 11 Mtpa across assets by 2035","Tied to North Field LNG","Permanent storage"],
    summary:"~4 Mtpa by 2030, tied to North Field LNG.",
    detail:"CO2 capture tied to North Field LNG, targeting about 4 million tonnes a year by 2030 and more than 11 Mtpa across QatarEnergy assets by 2035. Operational capture, not a credit listing.",
    url:"https://www.qatarenergy.qa/"
  },
  {
    id:"hajar", name:"44.01 Project Hajar", flag:"🇴🇲", cc:"OMN", country:"Oman",
    type:"capture", nature:"Removal", status:"Development", lat:22.9, lon:58.4,
    area:"Al Qabil concession", annual:"Scaling", std:"Mineralisation removal", methodology:"Direct air capture plus peridotite mineralisation",
    registry:"Removal credits", vintage:"Early issuances", lifetime:"Permanent", developer:"44.01 with Oman Ministry of Energy and Minerals",
    price:"Premium", priceUnit:"permanent removal credits",
    coBenefits:["World-first commercial peridotite mineralisation","Permanent, high-durability removal","XPRIZE-recognised"],
    summary:"World-first peridotite mineralisation, permanent removal credits.",
    detail:"The world's first commercial-scale peridotite mineralisation concession, at Al Qabil in the Hajar Mountains, pairing direct air capture with permanent mineralisation in Oman's Samail Ophiolite. Unlike the oil and gas CCS projects, this generates premium permanent removal credits, the highest-durability category in the voluntary market and directly relevant to corporate net-zero buyers.",
    url:"https://www.4401.earth/"
  },
  {
    id:"benban", name:"Benban Solar Park", flag:"🇪🇬", cc:"EGY", country:"Egypt",
    type:"renewable", nature:"Reduction", status:"Active", lat:24.46, lon:32.74,
    area:"~1.8 GW", annual:"~2,000,000 tCO₂e/yr avoided", std:"Global Carbon Council", methodology:"Grid-connected renewable electricity",
    registry:"Global Carbon Council", vintage:"Issuing", lifetime:"25 years", developer:"Multiple IPPs in the park",
    price:"Reduction", priceUnit:"avoided-emissions credits",
    coBenefits:["One of the world's largest solar complexes","Jobs and grid capacity","Displaces fossil generation"],
    summary:"~1.8 GW solar near Aswan, ~2M tonnes a year avoided.",
    detail:"One of the world's largest solar complexes, about 1.8 GW near Aswan, cutting roughly 2 million tonnes of CO2 a year. Several developers in the park are registered as carbon projects, mostly under the Global Carbon Council. As avoided-emissions reduction credits from grid renewables, additionality is increasingly questioned as solar becomes cost-competitive, which weighs on pricing.",
    url:"https://globalcarboncouncil.com/"
  },
  {
    id:"tafila", name:"Tafila Wind Farm", flag:"🇯🇴", cc:"JOR", country:"Jordan",
    type:"renewable", nature:"Reduction", status:"Active", lat:30.8, lon:35.6,
    area:"117 MW", annual:"~224,000 tCO₂e/yr avoided", std:"CDM / VCS", methodology:"Grid-connected wind power",
    registry:"CDM / Verra", vintage:"Issuing", lifetime:"20 years", developer:"Jordan Wind Project Company",
    price:"Reduction", priceUnit:"avoided-emissions credits",
    coBenefits:["Region's first utility-scale wind","Energy security","Local employment"],
    summary:"117 MW, the region's first utility-scale wind farm.",
    detail:"Jordan and the region's first utility-scale wind farm, 117 MW in Tafila, avoiding about 224,000 tonnes of CO2 a year versus conventional generation. A pioneering renewable project; as with solar, grid-renewable credits face additionality scrutiny.",
    url:"https://jordanwind.com/"
  },
  {
    id:"sharjahwte", name:"Sharjah Waste-to-Energy", flag:"🇦🇪", cc:"UAE", country:"United Arab Emirates",
    type:"waste", nature:"Reduction", status:"Active", lat:25.3, lon:55.5,
    area:"30 MW", annual:"~450,000 tCO₂e/yr displaced", std:"Operational", methodology:"Waste-to-energy, landfill diversion",
    registry:"Operational", vintage:"Since 2022", lifetime:"Asset life", developer:"Bee'ah and Masdar (Emirates Waste to Energy)",
    price:"Reduction", priceUnit:"avoided-emissions credits",
    coBenefits:["Region's first commercial WtE plant","Diverts waste from landfill","Phase-two expansion announced"],
    summary:"Region's first commercial waste-to-energy plant.",
    detail:"The region's first commercial-scale waste-to-energy plant, operating since 2022, displacing nearly 450,000 tonnes of CO2 a year by diverting waste from landfill and gas-fired power. A Bee'ah and Masdar joint venture with a phase-two expansion announced. Waste-to-energy credits hinge on the avoided-methane baseline.",
    url:"https://www.beeahgroup.com/"
  }
];
