/* Sifr Collection, MENA carbon schemes and regulation tracker.
   Real, public schemes. Can be regenerated by the daily data-refresh job. */
window.SIFR_SCHEMES = {
  updated: "2026-06-22",
  items: [
    {
      id:"rvcmc", name:"RVCMC", full:"Regional Voluntary Carbon Market Company", cc:"KSA", country:"Saudi Arabia",
      kind:"Voluntary market", status:"Active",
      summary:"Saudi voluntary carbon market operator, PIF and Tadawul owned.",
      detail:"Owned 80% by the Public Investment Fund and 20% by Tadawul. Has auctioned over 6.1 million tonnes across three events (2022 to 2024) and launched a regional voluntary carbon exchange. In June 2025 it signed a single agreement with Enowa, NEOM's energy and water subsidiary, targeting delivery of more than 30 million tonnes of credits by 2030. That is one bilateral deal, not a portfolio. The company now trades as VCM; RVCMC is the former name.",
      url:"https://vcm.sa/"
    },
    {
      id:"gcom", name:"GCOM", full:"Greenhouse Gas Crediting and Offsetting Mechanism", cc:"KSA", country:"Saudi Arabia",
      kind:"Crediting mechanism", status:"Developing",
      summary:"Saudi national crediting and offsetting framework.",
      detail:"Saudi Arabia's own greenhouse gas crediting and offsetting mechanism, intended to credit domestic emission reductions and removals alongside the voluntary market. A national crediting standard rather than an exchange.",
      url:"https://www.vision2030.gov.sa/"
    },
    {
      id:"acx", name:"ACX", full:"AirCarbon Exchange", cc:"UAE", country:"United Arab Emirates",
      kind:"Exchange", status:"Active",
      summary:"World's first fully regulated carbon exchange and clearing house, in ADGM.",
      detail:"Operating in Abu Dhabi Global Market, ACX runs the first fully regulated carbon trading exchange and clearing house. Where RVCMC is an operator, ACX is live market infrastructure with regulated clearing.",
      url:"https://www.aircarbon.co/"
    },
    {
      id:"adgm", name:"ADGM carbon regulation", full:"Abu Dhabi Global Market carbon framework", cc:"UAE", country:"United Arab Emirates",
      kind:"Regulation", status:"Active",
      summary:"First jurisdiction to regulate carbon credits as financial instruments.",
      detail:"ADGM became the world's first jurisdiction to regulate carbon credits and emission allowances as financial instruments, and to license exchanges and custodians to handle them. This is the legal backbone under ACX.",
      url:"https://www.adgm.com/"
    },
    {
      id:"uae-climate-law", name:"UAE Climate Law", full:"Federal Decree-Law No. 11 of 2024", cc:"UAE", country:"United Arab Emirates",
      kind:"Compliance regulation", status:"Active",
      summary:"Mandatory GHG reporting for all entities, full compliance by 30 May 2026.",
      detail:"The UAE's Federal Decree-Law on the Reduction of Climate Change Effects took effect on 30 May 2025 and requires all public and private entities, including in free zones, to report emissions and submit reduction plans, with full compliance by 30 May 2026 and penalties up to AED 2 million. The first binding corporate climate law in MENA, and a major demand driver for offsets.",
      url:"https://uaelegislation.gov.ae/en/legislations/2558"
    },
    {
      id:"egypt-vcm", name:"Egypt VCM", full:"Egypt voluntary carbon market", cc:"EGY", country:"Egypt",
      kind:"Voluntary market", status:"Active",
      summary:"Africa's first regulated voluntary carbon market, overseen by the FRA.",
      detail:"Egypt launched a regulated voluntary carbon market under the Financial Regulatory Authority, listing and trading credits on the Egyptian Exchange. A second large North African venue alongside the Gulf exchanges.",
      url:"https://fra.gov.eg/"
    },
    {
      id:"sgi", name:"Saudi Green Initiative", full:"Saudi Green Initiative", cc:"KSA", country:"Saudi Arabia",
      kind:"National initiative", status:"Active",
      summary:"10 billion trees and net zero by 2060, the demand backdrop for credits.",
      detail:"The Kingdom's flagship greening and decarbonisation programme: 10 billion trees, more than 100 million mangroves by 2030, and net zero by 2060. Not a market, but it sets the supply pipeline and political backdrop for regional credits.",
      url:"https://www.sgi.gov.sa/"
    },
    {
      id:"uae-ncsp", name:"UAE Carbon Sequestration", full:"National Carbon Sequestration Project", cc:"UAE", country:"United Arab Emirates",
      kind:"National initiative", status:"Active",
      summary:"100 million mangroves by 2030, 30M+ already planted.",
      detail:"The UAE's National Carbon Sequestration Project targets 100 million mangroves by 2030, with more than 30 million already planted, using drone-assisted planting and tissue culture. A national supply-side blue carbon programme.",
      url:"https://www.moccae.gov.ae/"
    }
  ]
};
